<a href="https://colab.research.google.com/github/Tower5954/TensorFlow/blob/main/Natural_Language_Processing_with_TensorFlow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to NLP fundamentals in TensorFlow

NLP has the goal of deriving information out of natural language (could be sequences of text or speech).

Another common term for NLP problems is sequence to sequence problems (seq2seq).

### Check GPU

In [1]:
!nvidia-smi -L

GPU 0: Tesla T4 (UUID: GPU-fe2752b5-fac4-bc4c-89b8-1ae7407c94be)


### Get helper-functions

In [2]:
!wget https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py

--2022-03-17 09:38:40--  https://raw.githubusercontent.com/mrdbourke/tensorflow-deep-learning/main/extras/helper_functions.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10246 (10K) [text/plain]
Saving to: ‘helper_functions.py’

helper_functions.py 100%[===================>]  10.01K  --.-KB/s    in 0s      

2022-03-17 09:38:40 (89.4 MB/s) - ‘helper_functions.py’ saved [10246/10246]



#### Import a series of helper functions for the notebook

In [3]:
from helper_functions import unzip_data, create_tensorboard_callback, plot_loss_curves, compare_historys

### Get a text dataset

The dataset that we are going to be using is Kaggle's introduction to NLP dataset (text samples of tweetslabelled as 'Disaster' or 'Not Disaster').

See the original source here: https://www.kaggle.com/c/nlp-getting-started/data

In [4]:
!wget https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip

# Unzip the data
unzip_data("nlp_getting_started.zip")

--2022-03-17 09:38:43--  https://storage.googleapis.com/ztm_tf_course/nlp_getting_started.zip
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.164.144, 142.251.45.112, 172.253.62.128, ...
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.164.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 607343 (593K) [application/zip]
Saving to: ‘nlp_getting_started.zip’

nlp_getting_started 100%[===================>] 593.11K  --.-KB/s    in 0.02s   

2022-03-17 09:38:43 (35.4 MB/s) - ‘nlp_getting_started.zip’ saved [607343/607343]



## Visualising a text dataset

To visualise our text samples, we first have to read them in, one way is to use Python: https://realpython.com/read-write-files-python/

Another way to do this is to use Pandas...

In [5]:
import pandas as pd

train_df = pd.read_csv("train.csv")
test_df = pd.read_csv("test.csv")

train_df.head()

id keyword location                                               text  \
0   1     NaN      NaN  Our Deeds are the Reason of this #earthquake M...   
1   4     NaN      NaN             Forest fire near La Ronge Sask. Canada   
2   5     NaN      NaN  All residents asked to 'shelter in place' are ...   
3   6     NaN      NaN  13,000 people receive #wildfires evacuation or...   
4   7     NaN      NaN  Just got sent this photo from Ruby #Alaska as ...   

   target  
0       1  
1       1  
2       1  
3       1  
4       1

In [6]:
train_df["text"][0]

'Our Deeds are the Reason of this #earthquake May ALLAH Forgive us all'

In [7]:
train_df["text"][1]

'Forest fire near La Ronge Sask. Canada'

In [8]:
# Shuffle training dataset

train_df_shuffle = train_df.sample(frac=1, random_state=42)
train_df_shuffle.head()

id      keyword               location  \
2644  3796  destruction                    NaN   
2227  3185       deluge                    NaN   
5448  7769       police                     UK   
132    191   aftershock                    NaN   
6845  9810       trauma  Montgomery County, MD   

                                                   text  target  
2644  So you have a new weapon that can cause un-ima...       1  
2227  The f$&amp;@ing things I do for #GISHWHES Just...       0  
5448  DT @georgegalloway: RT @Galloway4Mayor: ‰ÛÏThe...       1  
132   Aftershock back to school kick off was great. ...       0  
6845  in response to trauma Children of Addicts deve...       0

In [9]:
# What does the test dataframe look like?
test_df.head()

id keyword location                                               text
0   0     NaN      NaN                 Just happened a terrible car crash
1   2     NaN      NaN  Heard about #earthquake is different cities, s...
2   3     NaN      NaN  there is a forest fire at spot pond, geese are...
3   9     NaN      NaN           Apocalypse lighting. #Spokane #wildfires
4  11     NaN      NaN      Typhoon Soudelor kills 28 in China and Taiwan

In [10]:
# How many examples of each class?
train_df.target.value_counts()

0    4342
1    3271
Name: target, dtype: int64

In [11]:
# How many total samples?
len(train_df), len(test_df)

(7613, 3263)

In [12]:
# Visualise some random training examples
import random

random_index = random.randint(0, len(train_df)-5) # Create random indexes not higher than the total number of samples 
for row in train_df_shuffle[["text", "target"]][random_index:random_index+5].itertuples():
  _, text, target = row
  print(f"Target: {target}", "(real disaster)" if target > 0 else "(not real disaster)")
  print(f"Text:\n{text}\n")
  print("---\n")

Target: 0 (not real disaster)
Text:
Do you feel engulfed with low self-image? Take the quiz: http://t.co/YzDmouXQBO http://t.co/PeXfgawrG1

---

Target: 1 (real disaster)
Text:
Investigators shift focus to cause of fatal Waimate fire http://t.co/GoeTJGIhOp

---

Target: 0 (not real disaster)
Text:
First Time Playing Hearthstone on PC Thoughts http://t.co/aBoLxMH1vy

---

Target: 1 (real disaster)
Text:
Damage to school bus on 80 in multi car crash #BREAKING 

---

Target: 1 (real disaster)
Text:
@PrablematicLA @Adweek I'm actually currently dressed for a snowstorm...despite being in the middle of a Texas summer. Thanks office A/C.

---



### Split data into training and validation sets


Since the test set has no labels and we need a way to evalaute our trained models, we'll split off some of the training data and create a validation set.

When our model trains (tries patterns in the Tweet samples), it'll only see data from the training set and we can see how it performs on unseen data using the validation set.

We'll convert our splits from pandas Series datatypes to lists of strings (for the text) and lists of ints (for the labels) for ease of use later.

To split our training dataset and create a validation dataset, we'll use Scikit-Learn's `train_test_split()` method and dedicate 10% of the training samples to the validation set.

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
# Use train_test_split to split training data into training and validation sets
train_sentences, val_sentences, train_labels, val_labels = train_test_split(train_df_shuffle["text"].to_numpy(),
                                                                            train_df_shuffle["target"].to_numpy(),
                                                                            test_size=0.1, # Use 10% of training data for validation split
                                                                            random_state=42) 

In [15]:
# Check the lengths
len(train_sentences), len(train_labels), len(val_sentences), len(val_labels)

(6851, 6851, 762, 762)

In [16]:
# Check the first 10 samples 
train_sentences[:10], train_labels[:10]

(array(['@mogacola @zamtriossu i screamed after hitting tweet',
        'Imagine getting flattened by Kurt Zouma',
        '@Gurmeetramrahim #MSGDoing111WelfareWorks Green S welfare force ke appx 65000 members har time disaster victim ki help ke liye tyar hai....',
        "@shakjn @C7 @Magnums im shaking in fear he's gonna hack the planet",
        'Somehow find you and I collide http://t.co/Ee8RpOahPk',
        '@EvaHanderek @MarleyKnysh great times until the bus driver held us hostage in the mall parking lot lmfao',
        'destroy the free fandom honestly',
        'Weapons stolen from National Guard Armory in New Albany still missing #Gunsense http://t.co/lKNU8902JE',
        '@wfaaweather Pete when will the heat wave pass? Is it really going to be mid month? Frisco Boy Scouts have a canoe trip in Okla.',
        'Patient-reported outcomes in long-term survivors of metastatic colorectal cancer - British Journal of Surgery http://t.co/5Yl4DC1Tqt'],
       dtype=object), array([0, 

## Converting text into numbers

* Tokenisation:
  * Straight mapping from token to number (can be modelled but quickly gets too big).

* Embedding:
  * Richer representation of relationships between tokens (can limit size + can be learned)


In NLP, there are two main concepts for turning text into numbers:

  * **Tokenization** - A straight mapping from word or character or sub-word to a numerical value. There are three main levels of tokenization:

1. Using **word-level tokenization** with the sentence "I love TensorFlow" might result in "I" being `0`, "love" being `1` and "TensorFlow" being `2`. In this case, every word in a sequence considered a single **token**.
2. **Character-level tokenization**, such as converting the letters A-Z to values `1-26`. In this case, every character in a sequence considered a single **token**.
3. **Sub-word tokenization** is in between word-level and character-level tokenization. It involves breaking invidual words into smaller parts and then converting those smaller parts into numbers. For example, "my favourite food is pineapple pizza" might become "my, fav, avour, rite, fo, oo, od, is, pin, ine, app, le, piz, za". After doing this, these sub-words would then be mapped to a numerical value. In this case, every word could be considered multiple **tokens**.

* **Embeddings** - An embedding is a representation of natural language which can be learned. Representation comes in the form of a feature vector. For example, the word "dance" could be represented by the 5-dimensional vector `[-0.8547, 0.4559, -0.3332, 0.9877, 0.1112]`. It's important to note here, the size of the **feature vector** is tuneable. There are two ways to use embeddings:
1. **Create your own embedding** - Once your text has been turned into numbers (required for an embedding), you can put them through an embedding layer (such as `tf.keras.layers.Embedding`) and an embedding representation will be learned during model training.
2. **Reuse a pre-learned embedding** - Many pre-trained embeddings exist online. These pre-trained embeddings have often been learned on large corpuses of text (such as all of Wikipedia) and thus have a good underlying representation of natural language. You can use a pre-trained embedding to initialize your model and fine-tune it to your own specific task.

In [17]:
import tensorflow as tf
from tensorflow.keras.layers.experimental.preprocessing import TextVectorization

In [18]:
# Use the default TextVectorization parameters

text_vectoriser = TextVectorization(max_tokens=10000, # how mant words in the vocabulary
                                    standardize="lower_and_strip_punctuation",
                                    split="whitespace",
                                    ngrams=None, # create groups of n-words?
                                    output_mode="int", # how to map tokens to numbers
                                    output_sequence_length=None, # how long do you want your sequences to be?
                                    pad_to_max_tokens = True)

In [19]:
# Find the average number of tokens (words) in the training tweets
train_sentences[0].split()

['@mogacola', '@zamtriossu', 'i', 'screamed', 'after', 'hitting', 'tweet']

In [20]:
len(train_sentences[0].split())

7

In [21]:
round(sum([len(i.split()) for i in train_sentences]))

102087

In [22]:
round(sum([len(i.split()) for i in train_sentences]) / len(train_sentences))

15

In [23]:
# Set up a text vectorization variables

max_vocab_length = 10000 # max number of words to have in our vocabulary
max_length = 15 # max length our sequences will be (e.g. how many words from a tweet does our model see)

text_vectoriser = TextVectorization(max_tokens=max_vocab_length,
                                    output_mode="int",
                                    output_sequence_length=max_length)

In [24]:
# Fit the text vectoriser to the training text
text_vectoriser.adapt(train_sentences)

In [25]:
# Create a sample sentence and tokenise it
sample_sentence = "There's a flood in my street!"
text_vectoriser([sample_sentence])

<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[264,   3, 232,   4,  13, 698,   0,   0,   0,   0,   0,   0,   0,
          0,   0]])>

In [26]:
# Choose a random sentence from the training dataset and tokenising it
random_sentence = random.choice(train_sentences)

In [27]:
print(f"Original text:\n {random_sentence}\n\n Vectorised version:")
text_vectoriser([random_sentence])


Original text:
 What Natural Disaster Are You When You Get Angry? http://t.co/q4gl3Dvhu1

 Vectorised version:


<tf.Tensor: shape=(1, 15), dtype=int64, numpy=
array([[ 55, 286,  75,  22,  12,  45,  12,  52, 909,   1,   0,   0,   0,
          0,   0]])>

In [28]:
# Get the unique words in the vocabulary
words_in_vocab = text_vectoriser.get_vocabulary() # get all the unique words in our training data
top_5_words = words_in_vocab[:5] # get the most common words
bottom_5_words = words_in_vocab[-5:] # get the least common words
print(f"No of words in vocab: {len(words_in_vocab)}")
print(f"Most common words used: {top_5_words}")
print(f"Least common words used: {bottom_5_words}")

No of words in vocab: 10000
Most common words used: ['', '[UNK]', 'the', 'a', 'in']
Least common words used: ['pages', 'paeds', 'pads', 'padres', 'paddytomlinson1']


### Creating an Embedding using an Embedding Layer


To make the embedding we are going to use TensorFlow's embedding layer:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding


The parameters we care most about for our embedding layer:
* `input_dim` = the size of our vocabulary.
* `output_dim` = the size of the output embedding vector, for example, a value of 100 would mean each token getting represented by a vector 100 long.
* `input_length` = length of sequences being passed to the embedding layer.  

In [32]:
from tensorflow.keras import layers

embedding = layers.Embedding(input_dim=max_vocab_length, # set input shape
                             output_dim=128, # output shape # NN work best with numbers divisible by 8 
                             embeddings_initializer="uniform", # default
                             input_length=max_length # how long is each input
                             )

embedding

In [33]:
# Choose a random sentence from the training set
random_sentence = random.choice(train_sentences)
print(f"Original text:\n {random_sentence}\n\n Embedded version:")

# Embed the random sentence (turn it into dense vectors of fixed sizes)
sample_embed = embedding(text_vectoriser([random_sentence]))
sample_embed



Original text:
 Mourning notices for stabbing arson victims stir ‰Û÷politics of grief‰Ûª in Israel: Posters for Shira Banki and A... http://t.co/3GZ5zQQTHe

 Embedded version:


<tf.Tensor: shape=(1, 15, 128), dtype=float32, numpy=
array([[[ 0.03913904,  0.03351459, -0.04128531, ...,  0.0095441 ,
         -0.00467023, -0.0311168 ],
        [ 0.0353845 , -0.03905164, -0.04501357, ..., -0.04647784,
         -0.0205519 , -0.02920984],
        [ 0.00251591,  0.02608057,  0.04041337, ..., -0.00671686,
          0.04082756, -0.0274038 ],
        ...,
        [-0.01767296,  0.00061647,  0.01342008, ..., -0.00962697,
         -0.04588554, -0.03157233],
        [ 0.00251591,  0.02608057,  0.04041337, ..., -0.00671686,
          0.04082756, -0.0274038 ],
        [-0.04883932,  0.01266396, -0.02050072, ...,  0.03064502,
         -0.04102155,  0.0475433 ]]], dtype=float32)>

In [35]:
# Check out a single token's embedding
sample_embed[0][0], sample_embed[0][0].shape, random_sentence


(<tf.Tensor: shape=(128,), dtype=float32, numpy=
 array([ 0.03913904,  0.03351459, -0.04128531,  0.00569568, -0.01092118,
        -0.01103882,  0.03947682, -0.00614012,  0.01313032,  0.00240984,
         0.02485457,  0.02264135,  0.04311656,  0.02493099,  0.04156208,
         0.0121595 , -0.03785093, -0.04309293,  0.03077281, -0.02438426,
         0.01281805,  0.03314337, -0.01846727,  0.02260059,  0.03241215,
         0.00599592, -0.04361401, -0.00052309,  0.01376457,  0.02718184,
        -0.04838584,  0.03814362, -0.00849181, -0.00657899,  0.04478208,
        -0.04871032, -0.01597731, -0.04169527,  0.02766016,  0.03402296,
        -0.03495344, -0.04139505,  0.00146245,  0.01185029, -0.02482705,
        -0.0445375 , -0.01679956, -0.03483206,  0.00935638, -0.00739443,
         0.00251298,  0.02600081, -0.0301079 , -0.03535911,  0.04371944,
        -0.02134351, -0.02082049, -0.04680132,  0.0015973 , -0.02910438,
         0.0411183 ,  0.0363052 ,  0.04270476, -0.02508593, -0.01895058,
  